### ISSUE TITLE
ERROR: Couldn't install package: nba

### ISSUE THREAD

**Issue by johnfelipe** [pauldes/nba-mvp-prediction#7]
pipenv install --dev

    Creating a virtualenv for this project...
    Pipfile: /root/nba-mvp-prediction/Pipfile
    Using /usr/bin/python3.8 (3.8.5) to create virtualenv...
    ⠼ Creating virtual environment...created virtual environment CPython3.8.5.final.0-64 in 220ms
      creator CPython3Posix(dest=/root/.local/share/virtualenvs/nba-mvp-prediction-ryI8hl5S, clear=False, no_vcs_ignore=False, global=False)
      seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/root/.local/share/virtualenv)
        added seed packages: pip==21.1.2, setuptools==57.0.0, wheel==0.36.2
      activators BashActivator,CShellActivator,FishActivator,PowerShellActivator,PythonActivator,XonshActivator
    ✔ Successfully created virtual environment!
    Virtualenv location: /root/.local/share/virtualenvs/nba-mvp-prediction-ryI8hl5S
    Pipfile.lock (02346f) out of date, updating to (b951c0)...
    Locking [dev-packages] dependencies...
    Building requirements...
    ✔ Success!
    ✔ Success!
    Updated Pipfile.lock (b951c0)!
    Installing dependencies from Pipfile.lock (b951c0)...
    An error occurred while installing ./nba! Will try again.9
      🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 138/138 — 00:00:58
    Installing initially failed dependencies...
    [InstallError]:   File "/usr/local/lib/python3.8/dist-packages/pipenv/cli/command.py", line 233, in install
    [InstallError]:       retcode = do_install(
    [InstallError]:   File "/usr/local/lib/python3.8/dist-packages/pipenv/core.py", line 2052, in do_install
    [InstallError]:       do_init(
    [InstallError]:   File "/usr/local/lib/python3.8/dist-packages/pipenv/core.py", line 1304, in do_init
    [InstallError]:       do_install_dependencies(
    [InstallError]:   File "/usr/local/lib/python3.8/dist-packages/pipenv/core.py", line 899, in do_install_dependencies
    [InstallError]:       batch_install(
    [InstallError]:   File "/usr/local/lib/python3.8/dist-packages/pipenv/core.py", line 796, in batch_install
    [InstallError]:       _cleanup_procs(procs, failed_deps_queue, retry=retry)
    [InstallError]:   File "/usr/local/lib/python3.8/dist-packages/pipenv/core.py", line 703, in _cleanup_procs
    [InstallError]:       raise exceptions.InstallError(c.dep.name, extra=err_lines)
    [pipenv.exceptions.InstallError]: Processing ./nba
    [pipenv.exceptions.InstallError]:   DEPRECATION: A future pip version will change local packages to be built in-place without first copying to a temporary directory. We recommend you use --use-feature=in-tree-build to test your packages with this new behavior before it becomes the default.
    [pipenv.exceptions.InstallError]:    pip 21.3 will remove support for this functionality. You can find discussion regarding this at https://github.com/pypa/pip/issues/7555.
    [pipenv.exceptions.InstallError]: ERROR: Package 'nba' requires a different Python: 3.8.5 not in '==3.7.9'
    ERROR: Couldn't install package: nba
     Package installation failed...
      ☤  ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 0/1 — 00:00:01

how solve this, is possible use my actual python version 

    Python 3.8.5

**Comment by pauldes** [comment]
This projects has been built with Python 3.7.9, I recommend using the same version. I just updated the README with the right pipenv command (see https://github.com/pauldes/nba-mvp-prediction/commit/9156cef6300a2f124e6421896165658409abfa11). If you do not want to work with 3.7.9 I guess you wil have to update `Pipfile`, `Pipfile.lock`, and `nba/setup.py`.
